version: '3.8'

services:
  db-mysql:
    image: mysql:latest
    restart: always
    container_name: db-mysql
    environment:
      MYSQL_ROOT_PASSWORD: alianza
      MYSQL_DATABASE: alianza
      MYSQL_USER: admin
      MYSQL_PASSWORD: alianza
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql
  spring-boot-app:
    build:
      context: ./backend
    container_name: spring-boot-app
    ports:
      - "9001:9001"
    environment:
      - DATABASE_URL=jdbc:mysql://db-mysql:3306/alianza
      - DATABASE_USERNAME=admin
      - DATABASE_PASSWORD=alianza
    depends_on:
      - db-mysql

volumes:
  db_data: